CREATE TABLE IF NOT EXISTS Rating (
    rating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS Film (
    film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    release_date date,
    duration integer,
    rating int REFERENCES Rating(rating_id)
);

CREATE TABLE IF NOT EXISTS Genre (
    genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS FilmGenre (
    film_genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer REFERENCES Film(film_id) ON DELETE CASCADE,
    genre_id integer REFERENCES Genre(genre_id)
);

CREATE TABLE IF NOT EXISTS Users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar,
    login varchar,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS Status (
    status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS FilmLikes (
    film_likes_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer REFERENCES Film(film_id) ON DELETE CASCADE,
    user_id integer REFERENCES Users(user_id)
);

CREATE TABLE IF NOT EXISTS UserFriends (
    user_friends_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initial_user_id integer REFERENCES Users(user_id),
    second_user_id integer REFERENCES Users(user_id),
    status_id integer REFERENCES Status(status_id)
);